organization:
    id: 72a7a4f3-6c99-4ccd-95f9-aa1a5d425c7d
    name: MiddleMan
project:
    id: 08ea4145-9764-4cdb-ab5e-95321ac1beca
    slug: circleci/FAAkYqAViW3YHyi3A8FqoJ/26rKqTuqJ3enq775DQcddj
    name: MiddleMan
